version: "3"
services:
  springapp:
    build: .
    container_name: wordsl
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5000:5432
    restart: always
